### ISSUE TITLE
git test project issuses

### ISSUE THREAD

**Issue by renzhengeek** [renzhengeek/issues#26]
lvb:

```
ocfs2test@bj-ha-3:~/bin/ocfs2/log> cat multiple_run_2015-11-11-02-22.log
Partition has been mounted,should umount first to perform test
ocfs2test@bj-ha-3:~/bin/ocfs2/log> cat multiple-x86_64-2015-11-11-03-09-10.log
Wed Nov 11 03:09:10 EST 2015 - Starting Multiple Nodes Regress test
Tests with "-b 512 -C 4096"
Wed Nov 11 03:09:10 EST 2015
lvb_torture
2015/11/11,03:09:10  Mkfs device /dev/md0:
2015/11/11,03:09:10  /usr/bin/sudo -u root /sbin/mkfs.ocfs2 --fs-features=sparse,unwritten,inline-data -b 512 -C 4096 -L multi-lvb-torture-test -N 2   /dev/md0 
mkfs.ocfs2 1.8.2
Cluster stack: pcmk
Cluster name: cluster
Stack Flags: 0x0
NOTE: Feature extended slot map may be enabled
Overwriting existing ocfs2 partition.
Proceed (y/N): Label: multi-lvb-torture-test
Features: sparse extended-slotmap backup-super unwritten inline-data strict-journal-super xattr indexed-dirs refcount discontig-bg
Block size: 512 (9 bits)
Cluster size: 4096 (12 bits)
Volume size: 159865765888 (39029728 clusters) (312237824 blocks)
Cluster groups: 10890 (tail covers 3552 clusters, rest cover 3584 clusters)
Extent allocator size: 80740352 (77 groups)
Journal size: 33554432
Node slots: 2
Creating bitmaps: done
Initializing superblock: done
Writing system files: done
Writing superblock: done
Writing backup superblock: 4 block(s)
Formatting Journals: done
Growing extent allocator: done
Formatting slot map: done
Formatting quota files: done
Writing lost+found: done
mkfs.ocfs2 successful

2015/11/11,03:12:37  Mount volume from all nodes
2015/11/11,03:12:37  /home/ocfs2test/bin/ocfs2/bin/remote_mount.py -l multi-lvb-torture-test -m /mnt/shared/ -n bj-ha-3,bj-ha-5 
+ /usr/lib64/mpi/gcc/openmpi/bin/mpirun --allow-run-as-root -mca btl tcp,self -mca plm_rsh_agent ssh:rsh -np 2 --host bj-ha-3,bj-ha-5 /home/ocfs2test/bin/ocfs2/bin/command.py --mount -l multi-lvb-torture-test -m /mnt/shared/
2015/11/11,03:12:39  dd 2G testfile under mount point.
2097152+0 records in
2097152+0 records out
2147483648 bytes (2.1 GB) copied, 18.2402 s, 118 MB/s
2015/11/11,03:12:57  Run lvb_torture, CMD: /home/ocfs2test/bin/ocfs2/bin/run_lvb_torture.py -d /dlm/ -i 60000 -H /dev/md0 -l /home/ocfs2test/bin/ocfs2/log/lvb_torture/lvb_torture_2015-11-11-03-09.log -n bj-ha-3,bj-ha-5  F9F3CD74568B407FA34D649A9AAF1BC5 
--------------------------------------------------------------------------
mpirun has detected an attempt to run as root. This is *strongly*
discouraged as any mistake (e.g., in defining TMPDIR) or bug can
result in catastrophic damage to the OS file system, leaving
your system in an unusable state.

You can override this protection by adding the --allow-run-as-root
option to your cmd line. However, we reiterate our strong advice
against doing so - please do so at your own risk.
--------------------------------------------------------------------------
+ /usr/lib64/mpi/gcc/openmpi/bin/mpirun --allow-run-as-root -mca btl tcp,self -mca plm_rsh_agent ssh:rsh -mca btl_tcp_if_include em2 -np 2 --host bj-ha-3,bj-ha-5 /home/ocfs2test/bin/ocfs2/bin/lvb_torture -d /dlm/ -i 60000 F9F3CD74568B407FA34D649A9AAF1BC5
Runtime 228 seconds.

2015/11/11,03:12:58  Umount volume from all nodes.
2015/11/11,03:12:58  /home/ocfs2test/bin/ocfs2/bin/remote_umount.py -m /mnt/shared/ -n bj-ha-3,bj-ha-5
+ /usr/lib64/mpi/gcc/openmpi/bin/mpirun --allow-run-as-root -mca btl tcp,self -mca plm_rsh_agent ssh:rsh -np 2 --host bj-ha-3,bj-ha-5 /home/ocfs2test/bin/ocfs2/bin/command.py --umount -m /mnt/shared/
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[62621,1],0]
  Exit code:    1
--------------------------------------------------------------------------
2015/11/11,03:12:59  Remote umount failed

```

**Comment by renzhengeek** [comment]
kernel tar:

```

ocfs2test@bj-ha-3:~/bin/ocfs2/log> cat multiple-x86_64-2015-11-11-02-44-41.log
Wed Nov 11 02:44:41 EST 2015 - Starting Multiple Nodes Regress test
Tests with "-b 512 -C 4096"
Wed Nov 11 02:44:41 EST 2015
cross_delete
2015/11/11,02:44:41  Mkfs device /dev/md0:
2015/11/11,02:44:41  /usr/bin/sudo -u root /sbin/mkfs.ocfs2 --fs-features=sparse,unwritten,inline-data -b 512 -C 4096 -L multi-cross_delete-test -N 2   /dev/md0
mkfs.ocfs2 1.8.2
Cluster stack: pcmk
Cluster name: cluster
Stack Flags: 0x0
NOTE: Feature extended slot map may be enabled
Overwriting existing ocfs2 partition.
Proceed (y/N): Label: multi-cross_delete-test
Features: sparse extended-slotmap backup-super unwritten inline-data strict-journal-super xattr indexed-dirs refcount discontig-bg
Block size: 512 (9 bits)
Cluster size: 4096 (12 bits)
Volume size: 159865765888 (39029728 clusters) (312237824 blocks)
Cluster groups: 10890 (tail covers 3552 clusters, rest cover 3584 clusters)
Extent allocator size: 80740352 (77 groups)
Journal size: 33554432
Node slots: 2
Creating bitmaps: done
Initializing superblock: done
Writing system files: done
Writing superblock: done
Writing backup superblock: 4 block(s)
Formatting Journals: done
Growing extent allocator: done
Formatting slot map: done
Formatting quota files: done
Writing lost+found: done
mkfs.ocfs2 successful

2015/11/11,02:48:08  Mount volume from all nodes
2015/11/11,02:48:08  /home/ocfs2test/bin/ocfs2/bin/remote_mount.py -l multi-cross_delete-test -m /mnt/shared/ -n bj-ha-3,bj-ha-5
+ /usr/lib64/mpi/gcc/openmpi/bin/mpirun --allow-run-as-root -mca btl tcp,self -mca plm_rsh_agent ssh:rsh -np 2 --host bj-ha-3,bj-ha-5 /home/ocfs2test/bin/ocfs2/bin/command.py --mount -l multi-cross_delete-test -m /mnt/shared/
2015/11/11,02:48:09  Run cross_delete, CMD: /home/ocfs2test/bin/ocfs2/bin/cross_delete.py -c 1 -i em2 -d /mnt/shared//cross_delete_test -n bj-ha-3,bj-ha-5 -t ../tmp/linux-kernel.tar.gz
+ /usr/lib64/mpi/gcc/openmpi/bin/mpirun --allow-run-as-root -mca btl tcp,self -mca plm_rsh_agent ssh:rsh -mca btl_tcp_if_include em2 -np 2 --host bj-ha-3,bj-ha-5 /home/ocfs2test/bin/ocfs2/bin/crdel_gen_files.py -s /mnt/shared//cross_delete_test -l None -t ../tmp/linux-kernel.tar.gz
tar (child): ../tmp/linux-kernel.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
touch: cannot touch ‘None’: Permission denied
Traceback (most recent call last):
  File "/home/ocfs2test/bin/ocfs2/bin/crdel_gen_files.py", line 144, in <module>
    o2tf.untar(DEBUGON, dirlist[i], tarfile, logfile, '1')
  File "/home/ocfs2test/bin/ocfs2/bin/o2tf.py", line 186, in untar
    logfile, 0, '')
  File "/home/ocfs2test/bin/ocfs2/bin/o2tf.py", line 54, in printlog
    fd = open(logfile, 'a+', 0)
IOError: [Errno 13] Permission denied: 'None'
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[62040,1],1]
  Exit code:    1
--------------------------------------------------------------------------
Runtime 209 seconds.

2015/11/11,02:48:10  Umount volume from all nodes.
2015/11/11,02:48:10  /home/ocfs2test/bin/ocfs2/bin/remote_umount.py -m /mnt/shared/ -n bj-ha-3,bj-ha-5
+ /usr/lib64/mpi/gcc/openmpi/bin/mpirun --allow-run-as-root -mca btl tcp,self -mca plm_rsh_agent ssh:rsh -np 2 --host bj-ha-3,bj-ha-5 /home/ocfs2test/bin/ocfs2/bin/command.py --umount -m /mnt/shared/
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[62143,1],0]
  Exit code:    1
--------------------------------------------------------------------------
2015/11/11,02:48:11  Remote umount failed
ocfs2test@bj-ha-3:~/bin/ocfs2/log> cd ../bin/
ocfs2test@bj-ha-3:~/bin/ocfs2/bin> ll ../tmp/linux-kernel.tar.gz
-rwxrwxrwx 1 ocfs2test users 76453390 Nov  9 22:11 ../tmp/linux-kernel.tar.gz
ocfs2test@bj-ha-3:~/bin/ocfs2/bin> /home/ocfs2test/bin/ocfs2/bin/crdel_gen_files.py -s /mnt/shared//cross_delete_test -l None -t ../tmp/linux-kernel.tar.gz
Traceback (most recent call last):
  File "/home/ocfs2test/bin/ocfs2/bin/crdel_gen_files.py", line 115, in <module>
    fd = open(os.path.join(stagedir, socket.gethostname()+'_C.dat'), 'r', 0)
IOError: [Errno 2] No such file or directory: '/mnt/shared//cross_delete_test/bj-ha-3_C.dat'
ocfs2test@bj-ha-3:~/bin/ocfs2/bin> crdel_gen_files.py -s /mnt/shared//cross_delete_test -l None -t ../tmp/linux-kernel.tar.gz
Traceback (most recent call last):
  File "/home/ocfs2test/bin/ocfs2/bin/crdel_gen_files.py", line 115, in <module>
    fd = open(os.path.join(stagedir, socket.gethostname()+'_C.dat'), 'r', 0)
IOError: [Errno 2] No such file or directory: '/mnt/shared//cross_delete_test/bj-ha-3_C.dat'
ocfs2test@bj-ha-3:~/bin/ocfs2/bin> lsblk
NAME                MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
sda                   8:0    0 465.8G  0 disk
├─sda1                8:1    0     4G  0 part  [SWAP]
├─sda2                8:2    0    80G  0 part
├─sda3                8:3    0     1K  0 part
├─sda5                8:5    0    40G  0 part  /boot/grub2/i386-pc
└─sda6                8:6    0 341.8G  0 part  /home
sdb                   8:16   0 465.8G  0 disk
├─sdb1                8:17   0     4G  0 part  [SWAP]
├─sdb2                8:18   0    80G  0 part
└─sdb3                8:19   0 381.8G  0 part
  ├─target-test--01 254:0    0   100G  0 lvm
  ├─target-test--02 254:1    0   100G  0 lvm
  └─target-test--03 254:2    0   100G  0 lvm
sdc                   8:32   0   149G  0 disk
└─md0                 9:0    0 148.9G  0 raid1 /mnt/shared
sdd                   8:48   0   149G  0 disk
└─md0                 9:0    0 148.9G  0 raid1 /mnt/shared
sde                   8:64   0   500M  0 disk
sr0                  11:0    1  1024M  0 rom
ocfs2test@bj-ha-3:~/bin/ocfs2/bin> ll /mnt/shared/cross_delete_test/
total 0
drwxr-xr-x 3 ocfs2test users 312 Nov 11 02:48 bj-ha-3_0
drwxr-xr-x 3 ocfs2test users 312 Nov 11 02:49 bj-ha-5_0




the tar ball of linux-git.tar.gz can unzip normally by manually.

```
